package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	graphql1 "github.com/monandkey/panforyou/internal/pkg/infrastructure/graphql"
	"github.com/monandkey/panforyou/internal/pkg/usecase/model"
)

// Breads is the resolver for the breads field.
func (r *queryResolver) Breads(ctx context.Context) ([]*model.Bread, error) {
	return r.controller.List(ctx)
}

// Bread is the resolver for the bread field.
func (r *queryResolver) Bread(ctx context.Context, id string) (*model.Bread, error) {
	return r.controller.GetByID(ctx, id)
}

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
